version: "3.8"

services:
  elixir:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "1.13.0"
        PHOENIX_VERSION: "1.5.8"
        NODE_VERSION: "17.3.0"
    volumes:
      - ..:/workspace:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Phoenix1234
      POSTGRES_DB: rumbl_dev

volumes:
  postgres-data:
